# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_test1(self):
        self.driver.get("https://app.novafi.xyz/")
        self.driver.set_window_size(2560, 1330)
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".btn:nth-child(4) > span").click()

        self.driver.find_element(
            By.CSS_SELECTOR, ".modalWalletNotFound > .fas").click()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(5)").click()
        self.vars["win3175"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win3175"])
